# This is a basic workflow to help you get started with Actions

name: AutoGerber

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
    - '**.kicad_sch'
    - '**.kicad_pcb'
  pull_request:
    branches: [ main ]
    paths:
    - '**.kicad_sch'
    - '**.kicad_pcb'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Production_Files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: INTI-CMNB/KiBot@v2_k7
      with:
      # Required - kibot config file
        config: JLC.kibot.yaml
      # optional - prefix to output defined in config
        dir: CORE/outputs
      # optional - schematic file
        schema: 'CORE/MIDI_DIN.kicad_sch'
      # optional - PCB design file
        board: 'CORE/MIDI_DIN.kicad_pcb'
      # optional - verbose output info
        verbose: 0
    - uses: INTI-CMNB/KiBot@v2_k7
      with:
      # Required - kibot config file
        config: JLC.kibot.yaml
      # optional - prefix to output defined in config
        dir: FRONT/outputs
      # optional - schematic file
        schema: 'FRONT/MIDI_DIN_front.kicad_sch'
      # optional - PCB design file
        board: 'FRONT/MIDI_DIN_front.kicad_pcb'
      # optional - verbose output info
        verbose: 0
    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: ProdFiles
        path: |
          CORE/outputs/
          FRONT/outputs/
